### ISSUE TITLE
Can I use the nasality FFT script to slice an oral vowel ?

### ISSUE THREAD

**Issue by ghost** [stylerw/styler_praat_scripts#1]
Hello Styler,

I'm a phd student studying nasal vowels and beginner of nasality. I don't know how to reach you so I write my question here...

I am trying to do a pre-study to see (instead of read) some acoustic correlates of nasality by comparing FFT slice at the middle of /a i u/ produced in /pVp/ vs /mVm/ (so pap vs mam) and I found your script.

My question is : can I use https://github.com/stylerw/styler_praat_scripts/blob/master/nasality_automeasure/nasality_FFT.praat to have a slice of an oral vowel and compare it with it's nasalized version ?

I had a look at your script. Besides the difference of iteration, it seems that you use        
**Extract windowed selection... slice Hamming 1.0 1** 
for the nasal version and 
**Extract windowed selection... FFT_'milliseconds'ms Kaiser2 2 no**
for the oral version here https://github.com/stylerw/styler_praat_scripts/blob/master/fft_slicer.praat

Could you please clarify the use of different windows ? Nasality is quite a monster so I don't want to mess with it 🗡 

Hope you will see this post !

Sincerely
XW

**Comment by stylerw** [comment]
Hi XW!

Yes, the nasality_fft.praat script will work with oral vowels as well.  And the different windows don't have a very strong effect, in my experience.  Either kind would work there.  The important part of the nasality_fft script is the extract and iterate step.  

As for nasality, it's a huge monster!  Good luck!

Will

**Comment by ghost** [comment]
Tks for your quick reply styler ! Yes I just experienced with different windows and it was almost the same. I think I'll need to read some DSP books to have a better understanding. Do you have some books to recommend ?

Tks in advance！
Sincerely
XW
